package com.showcase.search.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@ApiModel(value="CatalogProductCategory", description="Resource representing a product category in the APN catalog")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Category {
    /** Unique category id */
    @ApiModelProperty(example = "1" , notes = "Unique category id generated by the system")
    private String id;

    /** Name of the category */
    @ApiModelProperty(example = "Books" , notes = "Name of the category under which this product is categorized")
    private String name;
}
