package com.showcase.search.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@ApiModel(value="SellerCatalogEntry", description="Resource representing a sellers catalog entry in the APN ecosystem")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Seller {
    /** Unique seller id */
    @ApiModelProperty(example = "1" , notes = "Unique seller id generated by the APN system")
    private String id;

    /** Unique seller id */
    @ApiModelProperty(example = "PartsBase" , notes = "Name of the Seller")
    private String name;

    /** Seller specific stock keeping unit */
    @ApiModelProperty(example = "SKU1234" , notes = "Stock keeping unit unique for a catalog entry for a seller")
    private String sku;
}
